drop table if exists journalist CASCADE;

create table journalist (
                            id bigint generated by default as identity,
                            email varchar(255),
                            first_name varchar(255) not null,
                            second_name varchar(255) not null,
                            primary key (id)
);